import { Module } from '@nestjs/common';
import { DatabaseModule } from './database/database.module';
import { ExamplesModule } from './database/examples.module';
import { CacheModule } from './cache/cache.module';
import { QueueModule } from './queue/queue.module';
import { RabbitMessagingModule } from './messaging/rabbitmq/rabbitmq.module';
import { KafkaMessagingModule } from './messaging/kafka/kafka.module';
import { AuthModule } from './auth/auth.module';
import { JwtAuthModule } from './auth/strategies/jwt/jwt-auth.module';
import { GoogleAuthModule } from './auth/strategies/google/google-auth.module';

/**
 * Generated by backend-template — aggregates the selected block modules.
 * Do not edit: this file is regenerated on each project generation.
 */
@Module({
  imports: [
    DatabaseModule,
    ExamplesModule,
    CacheModule,
    QueueModule,
    RabbitMessagingModule,
    KafkaMessagingModule,
    AuthModule,
    JwtAuthModule,
    GoogleAuthModule,
  ],
})
export class GeneratedModule {}
