import type { INestApplication } from '@nestjs/common';
import { connectRabbitMessaging } from './messaging/rabbitmq/rabbitmq.bootstrap';
import { connectKafkaMessaging } from './messaging/kafka/kafka.bootstrap';

/**
 * Generated by backend-template — runs the selected blocks' bootstrap hooks.
 * Do not edit: this file is regenerated on each project generation.
 */
export async function applyBootstrap(app: INestApplication): Promise<void> {
  await connectRabbitMessaging(app);
  await connectKafkaMessaging(app);
  await app.startAllMicroservices();
}
